plugins:
  anonymous_students_enabled:
    default: false
    client: false
  anonymous_students_category_id:
    default: -1
    client: false
  anonymous_students_username:
    default: 'Anonymous_Student'
    client: false
